# Based on https://github.com/argoproj/argo-cd/blob/v2.4.15/Dockerfile
# ARG BASE_ALPINE
FROM quay.io/argoproj/argocd:v2.4.15@sha256:85c7efc3e7f60fc0a6c039bf9aa303f4ae04172401c8bc48f34a82ec3ad99141 as artifact
